# Copyright (C) 2025  volodymyr-tsukanov  dropmoji
# for the full copyright notice see the LICENSE file in the root of repository
# app only + -it: podman run -it --rm --name nj --volume ./nextjs:/home/app -p 127.0.0.1:3005:3005 localhost/simple-nodejs:alpha ash

version: '3.8'

services:
  mongodb:
    image: docker.io/library/mongo:8.0-noble
    container_name: dropmoji-mongo-db_cnt
    volumes:
      - ./init-mongo.df.js:/docker-entrypoint-initdb.d/init-mongo.js
    ports:
      - "127.0.0.1:27017:27017"
    networks:
      - dropmoji-net

  app:
    image: localhost/simple-nodejs:alpha
    container_name: dropmoji-nj-app_cnt
    volumes:
      - ./nextjs:/home/app
    ports:
      - "127.0.0.1:3005:3005"
    command: tail -f /dev/null
    networks:
      - dropmoji-net
      - tunnel-net
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/dropmoji
    depends_on:
      - mongodb

  tunnel:
    image: docker.io/ngrok/ngrok:alpine
    container_name: dropmoji-nj-tl_cnt
    volumes:
      - ./init-ngrok.df.sec.yml:/etc/ngrok.yml
    networks:
      - tunnel-net
    command: ngrok http app:3005 --config=/etc/ngrok.yml
    depends_on:
      - app


networks:
  dropmoji-net:
    driver: bridge
  tunnel-net:
    driver: bridge
